package primed_drools.projectrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DomainScore implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer id;
   private java.lang.Integer domainId;
   private java.lang.Integer portfolioId;
   private java.lang.Integer programmeId;
   private java.lang.Integer projectId;
   private java.lang.Integer strategicObjectiveId;
   private java.lang.Integer kpikraId;
   private java.lang.Integer riskId;
   private java.lang.Integer projectBusinessImpactId;
   private java.lang.Integer projectCostId;
   private java.lang.String score;

   public DomainScore()
   {
   }

   public java.lang.Integer getId()
   {
      return this.id;
   }

   public void setId(java.lang.Integer id)
   {
      this.id = id;
   }

   public java.lang.Integer getDomainId()
   {
      return this.domainId;
   }

   public void setDomainId(java.lang.Integer domainId)
   {
      this.domainId = domainId;
   }

   public java.lang.Integer getPortfolioId()
   {
      return this.portfolioId;
   }

   public void setPortfolioId(java.lang.Integer portfolioId)
   {
      this.portfolioId = portfolioId;
   }

   public java.lang.Integer getProgrammeId()
   {
      return this.programmeId;
   }

   public void setProgrammeId(java.lang.Integer programmeId)
   {
      this.programmeId = programmeId;
   }

   public java.lang.Integer getProjectId()
   {
      return this.projectId;
   }

   public void setProjectId(java.lang.Integer projectId)
   {
      this.projectId = projectId;
   }

   public java.lang.Integer getStrategicObjectiveId()
   {
      return this.strategicObjectiveId;
   }

   public void setStrategicObjectiveId(java.lang.Integer strategicObjectiveId)
   {
      this.strategicObjectiveId = strategicObjectiveId;
   }

   public java.lang.Integer getKpikraId()
   {
      return this.kpikraId;
   }

   public void setKpikraId(java.lang.Integer kpikraId)
   {
      this.kpikraId = kpikraId;
   }

   public java.lang.Integer getRiskId()
   {
      return this.riskId;
   }

   public void setRiskId(java.lang.Integer riskId)
   {
      this.riskId = riskId;
   }

   public java.lang.Integer getProjectBusinessImpactId()
   {
      return this.projectBusinessImpactId;
   }

   public void setProjectBusinessImpactId(
         java.lang.Integer projectBusinessImpactId)
   {
      this.projectBusinessImpactId = projectBusinessImpactId;
   }

   public java.lang.Integer getProjectCostId()
   {
      return this.projectCostId;
   }

   public void setProjectCostId(java.lang.Integer projectCostId)
   {
      this.projectCostId = projectCostId;
   }

   public java.lang.String getScore()
   {
      return this.score;
   }

   public void setScore(java.lang.String score)
   {
      this.score = score;
   }

   public DomainScore(java.lang.Integer id, java.lang.Integer domainId,
         java.lang.Integer portfolioId, java.lang.Integer programmeId,
         java.lang.Integer projectId,
         java.lang.Integer strategicObjectiveId, java.lang.Integer kpikraId,
         java.lang.Integer riskId,
         java.lang.Integer projectBusinessImpactId,
         java.lang.Integer projectCostId, java.lang.String score)
   {
      this.id = id;
      this.domainId = domainId;
      this.portfolioId = portfolioId;
      this.programmeId = programmeId;
      this.projectId = projectId;
      this.strategicObjectiveId = strategicObjectiveId;
      this.kpikraId = kpikraId;
      this.riskId = riskId;
      this.projectBusinessImpactId = projectBusinessImpactId;
      this.projectCostId = projectCostId;
      this.score = score;
   }

}