package primed_drools.projectrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DomainScore implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DomainScore() {
    }

}