package primed_drools.projectrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PrimedFact implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private primed_drools.projectrules.Project project;
   private primed_drools.projectrules.DomainScore domainScore;

   public PrimedFact()
   {
   }

   public primed_drools.projectrules.Project getProject()
   {
      return this.project;
   }

   public void setProject(primed_drools.projectrules.Project project)
   {
      this.project = project;
   }

   public primed_drools.projectrules.DomainScore getDomainScore()
   {
      return this.domainScore;
   }

   public void setDomainScore(
         primed_drools.projectrules.DomainScore domainScore)
   {
      this.domainScore = domainScore;
   }

   public PrimedFact(primed_drools.projectrules.Project project,
         primed_drools.projectrules.DomainScore domainScore)
   {
      this.project = project;
      this.domainScore = domainScore;
   }

}