package primed_drools.projectrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProjectRelationShip implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "id")
   private java.lang.Integer id;
   private java.lang.Integer project1;
   private java.lang.Integer project2;
   private java.lang.Integer relationShipId;
   private java.lang.String relationShip;

   public ProjectRelationShip()
   {
   }

   public java.lang.Integer getId()
   {
      return this.id;
   }

   public void setId(java.lang.Integer id)
   {
      this.id = id;
   }

   public java.lang.Integer getProject1()
   {
      return this.project1;
   }

   public void setProject1(java.lang.Integer project1)
   {
      this.project1 = project1;
   }

   public java.lang.Integer getProject2()
   {
      return this.project2;
   }

   public void setProject2(java.lang.Integer project2)
   {
      this.project2 = project2;
   }

   public java.lang.Integer getRelationShipId()
   {
      return this.relationShipId;
   }

   public void setRelationShipId(java.lang.Integer relationShipId)
   {
      this.relationShipId = relationShipId;
   }

   public java.lang.String getRelationShip()
   {
      return this.relationShip;
   }

   public void setRelationShip(java.lang.String relationShip)
   {
      this.relationShip = relationShip;
   }

   public ProjectRelationShip(java.lang.Integer id,
         java.lang.Integer project1, java.lang.Integer project2,
         java.lang.Integer relationShipId, java.lang.String relationShip)
   {
      this.id = id;
      this.project1 = project1;
      this.project2 = project2;
      this.relationShipId = relationShipId;
      this.relationShip = relationShip;
   }

}