package primed_drools.projectrules;

import primed_drools.projectrules.Project;

rule "Match Name"
	when
		f1 : Project( id == 29 )
	then
		  System.out.println("Rule Match : ");
		  f1.setPriority("High");
		  
end

rule "Match RelationShip"
	when
		$f2 : Project(projectRelationShipList)
		
		 forall( Bus( this == $f2, relationship = 'ss' ) )
	then
				System.out.println("RelationShip Match : ");
	
end