package primed_drools.projectrules;

import primed_drools.projectrules.Project;
import primed_drools.projectrules.ProjectRelationShip;
rule "Match Name"
	when
		f1 : Project( id == 29 )
	then
		  System.out.println("Rule Match : ");
		  f1.setPriority("High");
		  
end

rule "Match RelationShip"
	when
     f2 : Project($pr : ProjectRelationShip)
     f3 : pr(relationship == "ss")
     
	then
			//	System.out.println("RelationShip Match : " +value);
	
end