package primed_drools.scorecalculator;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Project implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Project() {
    }

}